name: iterator-utilities
org: sapphire
install: true
packagePath: packages/iterator-utilities
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
