- name: blocked
  color: 'fc1423'
- name: bug:confirmed
  color: 'd73a4a'
- name: bug:unverified
  color: 'f9d0c4'
- name: chore
  color: 'ffffff'
- name: ci
  color: '0075ca'
- name: dependencies
  color: '276bd1'
- name: discordjs
  color: '5663e9'
- name: discussion
  color: 'b6b1f9'
- name: documentation
  color: '0075ca'
- name: duplicate
  color: 'cfd3d7'
- name: error handling
  color: 'ffff00'
- name: feature
  color: 'ffff00'
- name: hacktoberfest-accepted
  color: 'EE4700'
- name: has PR
  color: '4b1f8e'
- name: help wanted
  color: '008672'
- name: in progress
  color: 'ffccd7'
- name: in review
  color: 'aed5fc'
- name: invalid
  color: 'e4e669'
- name: need repro
  color: 'c66037'
- name: needs rebase & merge
  color: '24853c'
- name: packages:async-queue
  color: 'fbca04'
- name: packages:cron
  color: 'fbca04'
- name: packages:decorators
  color: 'fbca04'
- name: packages:discord-utilities
  color: 'fbca04'
- name: packages:discord.js-utilities
  color: 'fbca04'
- name: packages:duration
  color: 'fbca04'
- name: packages:eslint-config
  color: 'fbca04'
- name: packages:event-iterator
  color: 'fbca04'
- name: packages:fetch
  color: 'fbca04'
- name: packages:lexure
  color: 'fbca04'
- name: packages:phisherman
  color: 'fbca04'
- name: packages:prettier-config
  color: 'fbca04'
- name: packages:ratelimits
  color: 'fbca04'
- name: packages:result
  color: 'fbca04'
- name: packages:snowflake
  color: 'fbca04'
- name: packages:stopwatch
  color: 'fbca04'
- name: packages:string-store
  color: 'fbca04'
- name: packages:time-utilities
  color: 'fbca04'
- name: packages:timer-manager
  color: 'fbca04'
- name: packages:timestamp
  color: 'fbca04'
- name: packages:ts-config
  color: 'fbca04'
- name: packages:utilities
  color: 'fbca04'
- name: performance
  color: '80c042'
- name: priority:critical
  color: 'b60205'
- name: priority:high
  color: 'fc1423'
- name: question (please use Discord instead)
  color: 'd876e3'
- name: refactor
  color: '1d637f'
- name: regression
  color: 'ea8785'
- name: semver:major
  color: 'c10f47'
- name: semver:minor
  color: 'e4f486'
- name: semver:patch
  color: 'e8be8b'
- name: tests
  color: 'f06dff'
- name: typings
  color: '80c042'
- name: wontfix
  color: 'ffffff'
