- name: packages:async-queue
  color: 'fbca04'
- name: packages:bitfield
  color: 'fbca04'
- name: packages:cron
  color: 'fbca04'
- name: packages:decorators
  color: 'fbca04'
- name: packages:discord-utilities
  color: 'fbca04'
- name: packages:discord.js-utilities
  color: 'fbca04'
- name: packages:duration
  color: 'fbca04'
- name: packages:eslint-config
  color: 'fbca04'
- name: packages:eslint-plugin-result
  color: 'fbca04'
- name: packages:event-iterator
  color: 'fbca04'
- name: packages:fetch
  color: 'fbca04'
- name: packages:iterator-utilities
  color: 'fbca04'
- name: packages:lexure
  color: 'fbca04'
- name: packages:node-utilities
  color: 'fbca04'
- name: packages:phisherman
  color: 'fbca04'
- name: packages:prettier-config
  color: 'fbca04'
- name: packages:ratelimits
  color: 'fbca04'
- name: packages:result
  color: 'fbca04'
- name: packages:snowflake
  color: 'fbca04'
- name: packages:stopwatch
  color: 'fbca04'
- name: packages:string-store
  color: 'fbca04'
- name: packages:time-utilities
  color: 'fbca04'
- name: packages:timer-manager
  color: 'fbca04'
- name: packages:timestamp
  color: 'fbca04'
- name: packages:ts-config
  color: 'fbca04'
- name: packages:utilities
  color: 'fbca04'
- name: performance
  color: '80c042'
- name: priority:critical
  color: 'b60205'
- name: priority:high
  color: 'fc1423'
