name: '*next*'
verbose: true
package:
  - '@sapphire/async-queue'
  - '@sapphire/bitfield'
  - '@sapphire/cron'
  - '@sapphire/decorators'
  - '@sapphire/discord-utilities'
  - '@sapphire/discord.js-utilities'
  - '@sapphire/duration'
  - '@sapphire/eslint-config'
  - '@sapphire/event-iterator'
  - '@sapphire/fetch'
  - '@sapphire/node-utilities'
  - '@sapphire/phisherman'
  - '@sapphire/prettier-config'
  - '@sapphire/ratelimits'
  - '@sapphire/result'
  - '@sapphire/snowflake'
  - '@sapphire/stopwatch'
  - '@sapphire/time-utilities'
  - '@sapphire/timer-manager'
  - '@sapphire/timestamp'
  - '@sapphire/ts-config'
  - '@sapphire/utilities'
