name: '*next*'
verbose: true
package:
  - '@sapphire/async-queue'
  - '@sapphire/decorators'
  - '@sapphire/discord-utilities'
  - '@sapphire/discord.js-utilities'
  - '@sapphire/embed-jsx'
  - '@sapphire/eslint-config'
  - '@sapphire/event-iterator'
  - '@sapphire/fetch'
  - '@sapphire/prettier-config'
  - '@sapphire/ratelimits'
<<<<<<< HEAD
  - '@sapphire/results'
=======
  - '@sapphire/result'
>>>>>>> b77b5ebe00bbbed2da1e5258708c642cf535a0d9
  - '@sapphire/snowflake'
  - '@sapphire/stopwatch'
  - '@sapphire/time-utilities'
  - '@sapphire/ts-config'
  - '@sapphire/utilities'
  - '@sapphire/phisherman'