name: snowflake
org: sapphire
install: true
packagePath: packages/snowflake
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
