name: decorators
org: sapphire
install: true
packagePath: packages/decorators
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
