name: time-utilities
org: sapphire
install: true
packagePath: packages/time-utilities
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: sapphiredev/utilities
