name: timer-manager
org: sapphire
install: true
packagePath: packages/timer-manager
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
githubRepo: sapphiredev/utilities
