name: timestamp
org: sapphire
install: true
packagePath: packages/timestamp
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
