name: cron
org: sapphire
install: true
packagePath: packages/cron
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
