name: discord.js-utilities
org: sapphire
install: true
packagePath: packages/discord.js-utilities
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
