name: eslint-config
org: sapphire
install: true
packagePath: packages/eslint-config
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
