name: phisherman
org: sapphire
install: true
packagePath: packages/phisherman
identifierBase: false
pushTag: true
githubRelease: true
githubReleaseLatest: true
gitRepo: sapphiredev/utilities
gitHostVariant: github
