name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Add problem matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build ESLint, Prettier and Utilities
        run: |
          yarn turbo run build  \
            --filter=@sapphire/eslint-config \
            --filter=@sapphire/prettier-config \
            --filter=@sapphire/eslint-plugin-result \
            --filter=@sapphire/result \
            --filter=@sapphire/node-utilities \
            --filter=@sapphire/utilities
      - name: Run ESLint
        run: yarn lint --fix=false

  BuildingAndTesting:
    name: Building and Testing with node v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 19, 20, 21]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build Code
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Codecov Upload ${{ matrix.node }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/cobertura-coverage.xml
          flags: ${{ matrix.node }}
          fail_ci_if_error: true

  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Generate Documentation
        run: yarn docs

  Check_SubPath:
    name: Check SubPath
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Run Script
        run: yarn build:check-subpath -- --check

  Check_DynamicSideEffects:
    name: Check Dynamic Side Effects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.yarnpkg.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Validate dynamic side effects
        run: yarn build:dynamic-side-effects -- --check
