name: Continuous Delivery

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: The number of the PR that is being deployed
        required: false
        type: string
      ref:
        description: The branch that is being deployed. Should be a branch on the given repository
        required: false
        default: main
        type: string
      repository:
        description: The {owner}/{repository} that is being deployed.
        required: false
        default: sapphiredev/utilities
        type: string
  push:
    branches:
      - main

jobs:
  Publish:
    name: Publish Next to npm
    uses: sapphiredev/.github/.github/workflows/reusable-continuous-delivery.yml@main
    strategy:
      fail-fast: false
      matrix:
        package:
          - async-queue
          - bitfield
          - cron
          - decorators
          - discord-utilities
          - discord.js-utilities
          - duration
          - eslint-config
          - eslint-plugin-result
          - event-iterator
          - fetch
          - iterator-utilities
          - lexure
          - node-utilities
          - phisherman
          - ratelimits
          - result
          - snowflake
          - stopwatch
          - string-store
          - time-utilities
          - timer-manager
          - timestamp
          - ts-config
          - utilities
    with:
      build: true
      pr-number: ${{ github.event.inputs.prNumber }}
      ref: ${{ github.event.inputs.ref }}
      repository: ${{ github.event.inputs.repository }}
      working-directory: packages/${{ matrix.package }}
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
