name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - '**'

concurrency:
  group: ${{ github.workspace }}|${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  docgen:
    uses: sapphiredev/.github/.github/workflows/reusable-documentation-docgen.yml@main
    with:
      mono-repo: true

  upload:
    needs: docgen
    uses: sapphiredev/.github/.github/workflows/reusable-documentation-upload.yml@main
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        package:
          - async-queue
          - bitfield
          - cron
          - decorators
          - discord-utilities
          - discord.js-utilities
          - duration
          - event-iterator
          - fetch
          - iterator-utilities
          - lexure
          - node-utilities
          - phisherman
          - ratelimits
          - result
          - snowflake
          - stopwatch
          - string-store
          - time-utilities
          - timer-manager
          - timestamp
          - utilities
    with:
      project-name: utilities
      mono-repo: true
      name: ${{ needs.docgen.outputs.NAME }}
      type: ${{ needs.docgen.outputs.TYPE }}
      sha: ${{ needs.docgen.outputs.SHA }}
      package: ${{ matrix.package }}
      artifact-id: ${{ needs.docgen.outputs.artifact-id }}
    secrets:
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
